### PR TITLE
Add Docker steps

### PR DESCRIPTION
**Pull request by Macleykun**
Heya!

I saw ya just finished the auth :) great work! I have to check it out later this week but it's really handy!

Because the auth is (mostly) done, i wanted to try again with the Docker support!

The only things i need to figure out:

- [x] Make cron jobs editable from the host and readable in the container. Run crond (works) so that automation can happen within the container if wanted.
- [x] Make instructions and edit the run command to make the custom config mounted, so people can set the right light config.
- [x] Make it easy for people to add more users and keep these changes persistent.

Bonus:
- [x] If we can host an image on docker or GitHub, people will only have to download the image instead of locally building it. Another benefit is that people can auto-update as well!
- [x] automate the above in a ci/cd.

### CODE REVIEW

**Comment by Macleykun** [comment]
Hope ya ok to help/merge this PR :) there's a few things i would request to make the implementation even easier if that's ok!

**Comment by Macleykun** [comment]
if possible, i would like to propose to fetch the color for Cheerlights through the website/in the code itself?

Something like a toggle, field to fill in? I personally want to achieve a solution where people don't have to use the terminal at all, and instead just use portainer to get the container and configure the portainer or pixel website/dashboard.

**Comment by penguintutor** [comment]
I am not able to support a docker configuration at this time. It's something I will look into in future, but do not want to get issue requests for something I'm unable to support. It would also need additional tests which I'm unable to add at the moment. Using git / release downloads is easy to maintain at the moment.

The use of cron for the custom colour is intentional as it allows for other ways of changing the colour, not just using cheerlights. It also means that the web server can concentrate on serving pages and not need to periodically check the cheerlights website. I wouldn't want to have updates to the sequence delayed waiting for a http request. 

I will look at these again in future.

**Comment by Macleykun** [comment]
Fully understand :) i will let this PR open and improve on my fork and possibly try to make a solid docker image and docs so users can use/test it if they stumble upon it.

I do agree with you with cron and i've looked into it more and found a way to have the ease of use with cron while keeping the container more or less static.

I can run crond and pixel-server.py at the same time in the container which is great!
Instead of specifying the cron job in the Dockerfile, i'll mount the crontab from the host to the container. That way what happens on the host crontab will reflect in the container aswell.

Then it's as easy as adding it with using `crontab -e` for the user and all will be well :).

Once i played more with the new auth update, i'll probably do a simalair way for making users aswell!

---

Unrelated: Isn't it handy to maybe cleanup the branches ya no longer need?
image

**Comment by Macleykun** [comment]
I haven't tested the last changes yet, but by making them volumes and touching them during the build, nothing should be overwritten as the volume always overwrites whats in the container. Touch is needed or the volume wouldn't be able to mount.

In the comments of the Dockerfile, i included how people can edit the crontab and the other config files as well. I'll give it a try later this week and will report if it works (and ofc fix it).

To keep things simple, i'll host the images myself using github actions with github registery. 
https://github.com/brblacky/lavamusic/blob/main/.github/workflows/build-docker.yml

**Comment by Macleykun** [comment]
Heya! I finished up everything and included a CI/CD to both dockerhub and github registery (i would advice to only use one, as having two is unnecessary).

I've included the steps and i've tested this on a fresh install of the latest pi os.

I've also went ahead and update the readme a bit.

If ya want to merge this, you do need to choose which registery to use, make an account, a repository.
and fill in the action secrets the username and password of yourself.

Then every commit to main will update the image :).

After this, i'll remove my fork and container (also you must change the docker image names in the CI and readme to yours, otherwise people will still use mines :P).

Take ya time on this PR, i do hope you'll enjoy the time and effort i put into this :) it wasn't easy to figure some new stuff out haha.

**Comment by Macleykun** [comment]
Heya! Got a fun update to show!
https://youtu.be/HLGYNhvvlfQ

**Comment by Macleykun** [comment]
heya! wanted to ask if ya have been able to have a look at this PR and this issue: https://github.com/penguintutor/pixel-server/issues/9
hope ya doing well!

**Comment by penguintutor** [comment]
I don't think docker is necessary for this and would add additional complexity that I am not able to support. To use through docker means first installing docker, which adds one more step in the install process.

I may look at creating an installable deb package in future which I think will make install easier.

**Comment by Macleykun** [comment]
Heyo! Thanks for your reply first of all!
I admit, it’s not a necessary feature, it’s a nice to have admittedly!

The complexity might seen like much, but it’s not that much extra! I’ve automated the build process for us so you only have to look at the part of the code (which you already do) and meow the user is running it (this part I can always help out with! Just ping me and I’ll try to reply asap/within a day)!

The docker methode actually is different from what users have to do now. Instead of getting python, pip, libs and clone the project. They only need to pull 3 files and get docker and run the image! With one additional command they can also let it auto update itself!

I do respect your choice in the end regardless and I’ll try to keep the fork up to date!
If you ever need some help with docker, I’m always open to help!

also, I do hope you watched the video from novaspirit! He showed on video how users get the container and set it up and all. It actually seemed to work out of the box with the 52pi case!

**Pull request closed without merging**
