### PR TITLE
Add Dockerfile to enable Docker support (locally)

### PR DESCRIPTION
**Pull request by Macleykun**
A bit from this issue: https://github.com/penguintutor/pixel-server/issues/1

This PR focuses on adding a Dockerfile with the needed steps for a user to make a container image, to run the project with docker.

If you like, this image can be hosted on dockerhub and users only need to use the run command to use the project.
But, we do need to instruct the user to wget/download the config file, edit it, and then store it and use the volume parameter so that the container has persistant access to the config file.

If you do want to make a container image on the internet, i can also look into a CI/CD so that each commit/release triggers a new image version and updates the latest tag, so users can automatically update with watchtower!

### CODE REVIEW

**Comment by Macleykun** [comment]
Heya!
What ya think of this PR :) you like it?

If so, maybe you can publish the image on dockerhub for everyone to easily pull and setup their pixel-server!
Perhaps it's an idea to use env vars for this project aswell? That's alot easier to configure then using a config file :)
Or, we could just instruct users to download the config file (under the custom name) and mount to that!

I can then contribute it to this template community which makes it extremely easy for people to use their pixel devices!
https://github.com/novaspirit/pi-hosted

I hope you want to consider merging/working on this :)

**Comment by penguintutor** [comment]
Thanks for the PR, but unfortunately I don't have the time to maintain a docker setup at the moment, especially as the project is currently under actively development. For example a change I am currently working on will change the return values from the automation which could potentially break implementations that rely on consistent return values. 

If you would like to maintain your own docker images then feel free, but I'm not in a position to do so at the moment.

**Comment by Macleykun** [comment]
Sure np :) if possible I could make something in GitHub workflow to keep it auto maintained.

It’s basically a docker built, and push image to registry workflow. You technically only would need to make a docker account, a image page, set a secret on the GitHub repo (token) and the latest will always update itself per commit. And if it breaks it’ll send you a mail what went wrong in the build process.

would that make it easier/better? I personally prefer to not maintain it myself

**Comment by Macleykun** [comment]
Otherwise we can just include the Dockerfile without docs, or I’ll just close the pr and you can contact me to re-submit :)

**Comment by Macleykun** [comment]
heya, i worked a bit on this again and found the run command to run this with docker withoud --priviliged:

docker run --device=/dev/vcio --cap-add=SYS_RAWIO --device=/dev/mem --security-opt=systempaths=unconfined --security-opt=apparmor=unconfined --device=/dev/spidev0.0 --device=/dev/i2c-1 --device=/dev/gpiomem --restart unless-stopped -p 85:80 --name pixel-server pixel-server


it's a mouth full, but it does work :)
reason is b/c of this: https://github.com/moby/moby/issues/43419

**Comment by badsmoke** [comment]
i managed to start the container but nothing happens when i set something in the gui

**Comment by Macleykun** [comment]
> i managed to start the container but nothing happens when i set something in the gui
Did you do these commands on the host?

sudo raspi-config nonint do_spi 0
sudo raspi-config nonint do_i2c 0
ls /dev/i2c* /dev/spidev0.0

see https://github.com/Macleykun/pixel-server#docker-install

**Pull request closed without merging**
